In [1]:
from environment import EvaluationEnvironment
import numpy as np
from game import GlobalFeatureImportance, LocalFeatureImportance, UnsupervisedFeatureImportance
from plot import plot
import util

In [2]:
from algorithms.CMCS import *
from algorithms.GapE import GapE
from algorithms.SAR import SAR
from algorithms.ApproShapley import ApproShapley
from algorithms.BUS import BUS
from algorithms.SVARM import SVARM, StratSVARM
from algorithms.KernelSHAP import KernelSHAP
from algorithms.shap_k import SHAP_K
%load_ext autoreload
%autoreload 2
%matplotlib inline

c:\Users\Tim\miniconda3\envs\shapley\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
k=5
budget=1500
num_experiments=100
step_interval=50
env = EvaluationEnvironment()
results = []

In [4]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [5]:
filepath_global = "datasets/global/German credit classification random forest.csv"
filepath_unsupervised = "datasets/unsupervised/vf_BigFive.csv"
directory_local = "datasets/local/image_classification"
game = GlobalFeatureImportance(filepath=filepath_global, use_cached=True)
# game = LocalFeatureImportance(directory=directory_local, num_players=n)
# game = UnsupervisedFeatureImportance(filepath=filepath_unsupervised, num_players=n)

[0.000 0.000 -0.017 ... 0.057 0.040 0.060] 20
[0.030 0.009 0.006 -0.003 -0.004 0.010 0.002 0.003 -0.003 0.002 0.002
 0.006 -0.003 0.003 -0.003 0.000 0.002 -0.001 0.000 0.001] 0.05999999999998523


In [6]:
results += [("CMCS@K(T_min=30, delta=0.01)", *env.evaluate_fixed_k(game, CMCS_at_K(t_min=30, delta=0.01), k, budget, step_interval, num_experiments))]

[[0.000 0.000 0.000 ... 0.001 0.001 0.001]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 ...
 [0.000 0.000 0.000 ... 0.001 0.001 0.001]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]] (array([0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.001, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000]), array([0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000]))


In [7]:
results += [("CMCS", *env.evaluate_fixed_k(game, CMCS(), k, budget, step_interval, num_experiments))]

[[0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 ...
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.001 0.001 0.001]] (array([0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.001,
       0.001, 0.001, 0.001, 0.001, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000]), array([0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
       0.000, 0.000, 0.000]))


In [ ]:
results += [("SHAP@K(T_min=30, delta=0.01)", *env.evaluate_fixed_k(game, SHAP_K(t_min=30, delta=0.01), k, budget, step_interval, num_experiments))]

TypeError: PAC_Algorithm.__init__() got an unexpected keyword argument 'T_min'

In [ ]:
results += [("Greedy CMCS", env.evaluate(game, Greedy_CMCS(t_min=30, delta=0.01), k, step_interval, rounds))]

In [10]:
# results += [("CMCS", env.evaluate(game, CMCS(), k, step_interval, rounds))]

In [11]:
# results += [("StratSVARM", env.evaluate(game, StratSVARM(start_exact=False, theoretical_distribution=False), k, step_interval, rounds))]

In [17]:
results += [("ApproShapley", *env.evaluate_fixed_k(game, ApproShapley(), k, budget, step_interval, num_experiments))]

In [13]:
labels = {
    "mse": ("budget", "mse"),
    "ratio": ("budget", "ratio"),
    "numeric": ("budget", "numeric"),
    "epsilon": ("budget", "epsilon"),
}

In [14]:
results

[('CMCS@K(T_min=30, delta=0.01)',
  array([  50,  100,  150,  200,  250,  300,  350,  400,  450,  500,  550,
          600,  650,  700,  750,  800,  850,  900,  950, 1000, 1050, 1100,
         1150, 1200, 1250, 1300, 1350, 1400, 1450, 1500]),
  {'ratio': (array([0.198, 0.342, 0.466, 0.466, 0.466, 0.604, 0.580, 0.566, 0.554,
           0.530, 0.518, 0.558, 0.526, 0.508, 0.502, 0.480, 0.472, 0.466,
           0.464, 0.440, 0.448, 0.442, 0.444, 0.442, 0.448, 0.430, 0.442,
           0.434, 0.438, 0.438]),
    array([0.002, 0.009, 0.013, 0.013, 0.013, 0.017, 0.016, 0.016, 0.016,
           0.015, 0.015, 0.016, 0.014, 0.014, 0.014, 0.014, 0.015, 0.015,
           0.014, 0.016, 0.016, 0.016, 0.016, 0.016, 0.016, 0.017, 0.015,
           0.016, 0.016, 0.016])),
   'numeric': (array([0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
           0.000, 0.000, 0.010, 0.010, 0.000, 0.000, 0.000, 0.000, 0.000,
           0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
  

In [18]:
plot(results, labels, save=True, filepath=f"results/{game.__class__.__name__}({game.name})_k={k}_budget={budget}_r={num_experiments}.pdf")